# Generated by Django 5.2.4 on 2025-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('main_actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
            ],
        ),
    ]
